plugins {
	id 'io.freefair.lombok'
	id 'java'
}

dependencies {
	implementation project(':reva')
	api "org.eclipse.xtext:org.eclipse.xtext.ide:${xtextVersion}"
	api "org.eclipse.xtext:org.eclipse.xtext.xbase.ide:${xtextVersion}"
	api "com.google.guava:guava:30.1-jre"

	implementation "org.slf4j:slf4j-log4j12:${slf4jVersion}"
	
	testImplementation "org.eclipse.xtext:org.eclipse.xtext.testing:${xtextVersion}"
	testImplementation "junit:junit:${junitVersion}"
}

task runSpiProcesor(type: JavaExec) {
	mainClass = "reva.ide.SpiProcessor"
	classpath = sourceSets.main.runtimeClasspath
}

build.dependsOn runSpiProcesor