/*
 * generated by Xtext 2.33.0
 */
package reva.validation;

import org.eclipse.xtext.nodemodel.util.NodeModelUtils;
import org.eclipse.xtext.validation.Check;
import org.eclipse.xtext.validation.CheckType;
import org.eclipse.xtext.xbase.XExpression;

import org.eclipse.xtext.xbase.XNumberLiteral;
import org.eclipse.xtext.xbase.XStringLiteral;
import reva.diagnostics.Diagnostic;
import reva.revaDsl.PrintExpression;
import reva.revaDsl.RepeatExpression;
import reva.revaDsl.XVariableDeclaration;

/**
 * This class contains custom validation rules.
 *
 * <p>See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
public class RevaDslValidator extends AbstractRevaDslValidator {

  @Override
  protected boolean isValueExpectedRecursive(XExpression expr) {
    return expr.eContainer() instanceof PrintExpression //
        || expr.eContainer() instanceof RepeatExpression //
        || expr.eContainer() instanceof XVariableDeclaration
        || super.isValueExpectedRecursive(expr);
  }

  @Check(CheckType.EXPENSIVE)
  public void validateXExpression(XExpression expression) {
    if (expression.eContainer() instanceof PrintExpression
        && (expression instanceof XNumberLiteral || expression instanceof XStringLiteral)) {
      publishWarning(
          Diagnostic.RV001.getMessage()
              + NodeModelUtils.getTokenText(NodeModelUtils.getNode(expression)),
          Diagnostic.RV001.getCode());
    }
  }

  @Check(CheckType.NORMAL)
  public void validateRepeatExpression(RepeatExpression expression) {
    XExpression count = expression.getCount();

    if (!(count instanceof XNumberLiteral numberLiteral)) {
      return;
    }

    int countValue = Integer.parseInt(numberLiteral.getValue());

    if (countValue == 1) {
      publishWarning("Count should be greater than 1", "RV001");
    }
  }

  private void publishWarning(String message, String diagnosticCode) {
    warning(message, null, diagnosticCode);
  }
}
