plugins {
	id 'java'
	id 'org.springframework.boot' version '2.7.5'
	id 'io.spring.dependency-management' version '1.0.14.RELEASE'
}

dependencies {
	implementation project(':reva')
	implementation project(':reva.ide')
	implementation("org.springframework.boot:spring-boot-starter-websocket:${wsVersion}") {
		exclude group: 'org.springframework.boot', module: 'spring-boot-starter-logging'
	}
	implementation "org.slf4j:slf4j-log4j12:${slf4jVersion}"
}
