/*
 * generated by Xtext 2.33.0
 */
package reva.ide;

import com.google.inject.Binder;
import com.google.inject.TypeLiteral;
import com.google.inject.multibindings.MapBinder;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.xtext.formatting2.IFormatter2;
import org.eclipse.xtext.ide.server.ILanguageServerExtension;
import org.eclipse.xtext.ide.server.codeActions.ICodeActionService2;
import org.eclipse.xtext.ide.server.codelens.ICodeLensService;
import org.eclipse.xtext.ide.server.commands.IExecutableCommandService;
import org.eclipse.xtext.ide.server.contentassist.ContentAssistService;
import org.eclipse.xtext.service.SingletonBinding;
import org.eclipse.xtext.xbase.ide.contentassist.XbaseIdeContentProposalProvider;
import org.eclipse.xtext.xbase.typesystem.internal.IFeatureScopeTracker;
import reva.formatting2.RevaDslFormatter;
import reva.ide.codeactions.RevaCodeActionService;
import reva.ide.codelens.RevaCodeLensService;
import reva.ide.commands.RevaCommandsService;
import reva.ide.contentassist.RevaContentProposalProvider;
import reva.ide.contentassist.providers.PrintExpressionContentProposalProvider;
import reva.ide.contentassist.providers.RevaAbstractContentProposalProvider;
import reva.ide.endpoints.custom.RevaTextDocumentExtension;
import reva.revaDsl.PrintExpression;
import reva.typesystem.OptimizingFeatureScopeTrackerProvider2;

/** Use this class to register ide components. */
public class RevaDslIdeModule extends AbstractRevaDslIdeModule {

  @Override
  public void configure(Binder binder) {
    super.configure(binder);
    bindContentAssistProviders(binder);
  }

  public Class<? extends ContentAssistService> bindContentAssistService() {
    return ContentAssistService.class;
  }

  public Class<? extends XbaseIdeContentProposalProvider> bindXbaseIdeContentProposalProvider() {
    return RevaContentProposalProvider.class;
  }

  @Override
  public Class<? extends IFeatureScopeTracker.Provider> bindIFeatureScopeTrackerProvider() {
    return OptimizingFeatureScopeTrackerProvider2.class;
  }

  public Class<? extends ICodeActionService2> bindCodeActionService() {
    return RevaCodeActionService.class;
  }

  public Class<? extends ICodeLensService> bindCodeLensService() {
    return RevaCodeLensService.class;
  }

  public Class<? extends IExecutableCommandService> bindCommandsService() {
    return RevaCommandsService.class;
  }

  public Class<? extends IFormatter2> bindIFormatter2() {
    return RevaDslFormatter.class;
  }

  @SingletonBinding
  public Class<? extends ILanguageServerExtension> bindILanguageServerExtension() {
    return RevaTextDocumentExtension.class;
  }

  private void bindContentAssistProviders(Binder binder) {
    MapBinder<Class<? extends EObject>, RevaAbstractContentProposalProvider>
        contentAssistProvidersBinder =
            MapBinder.newMapBinder(binder, new TypeLiteral<>() {}, new TypeLiteral<>() {});

    contentAssistProvidersBinder
        .addBinding(PrintExpression.class)
        .toInstance(new PrintExpressionContentProposalProvider());
  }
}
