/*
 * generated by Xtext 2.33.0
 */
package reva.formatting2;

import org.eclipse.emf.ecore.EObject;
import org.eclipse.xtext.formatting2.IFormattableDocument;
import org.eclipse.xtext.formatting2.IHiddenRegionFormatter;
import org.eclipse.xtext.formatting2.ITextReplacer;
import org.eclipse.xtext.formatting2.ITextReplacerContext;
import org.eclipse.xtext.formatting2.regionaccess.IAstRegion;
import org.eclipse.xtext.formatting2.regionaccess.ISemanticRegion;
import org.eclipse.xtext.formatting2.regionaccess.ITextRegionRewriter;
import org.eclipse.xtext.formatting2.regionaccess.ITextReplacement;
import org.eclipse.xtext.formatting2.regionaccess.ITextSegment;
import org.eclipse.xtext.formatting2.regionaccess.internal.TextSegment;
import org.eclipse.xtext.nodemodel.ICompositeNode;
import org.eclipse.xtext.nodemodel.util.NodeModelUtils;
import org.eclipse.xtext.xbase.XExpression;
import org.eclipse.xtext.xbase.XVariableDeclaration;
import org.eclipse.xtext.xbase.formatting2.XbaseFormatter;
import org.eclipse.xtext.xbase.lib.Procedures;
import reva.revaDsl.Model;
import reva.revaDsl.PrintExpression;

import java.util.List;
import java.util.stream.StreamSupport;

public class RevaDslFormatter extends XbaseFormatter {
  Procedures.Procedure1<IHiddenRegionFormatter> ONE_SPACE = IHiddenRegionFormatter::oneSpace;
  Procedures.Procedure1<IHiddenRegionFormatter> NO_SPACE = IHiddenRegionFormatter::noSpace;
  Procedures.Procedure1<IHiddenRegionFormatter> NEW_LINE = IHiddenRegionFormatter::newLine;

  public void format(final Object expr, final IFormattableDocument doc) {
    if (expr instanceof Model) {
      format((Model) expr, doc);
      return;
    }
    if (expr instanceof PrintExpression printExpression) {
      format(printExpression, doc);
      return;
    }
    if (expr instanceof XVariableDeclaration) {
      _format((XVariableDeclaration) expr, doc);
      return;
    }
    super.format(expr, doc);
  }

  protected void format(Model model, IFormattableDocument doc) {
    for (XExpression xExpression : model.getExpressions()) {
      doc.format(xExpression);
    }
  }

  protected void format(PrintExpression printExpression, IFormattableDocument doc) {
    ISemanticRegion semanticRegion = regionForKeyword("print", printExpression);
    doc.append(semanticRegion, ONE_SPACE);
  }

  // TODO: implement for RepeatExpression, XVariableDeclaration
  private void addDocReplacement(EObject eObject, IFormattableDocument doc, String replacement) {
    ITextRegionRewriter rewriter = doc.getRegion().getTextRegionAccess().getRewriter();
    ICompositeNode node = NodeModelUtils.getNode(eObject);

    ITextReplacement textReplacement =
        rewriter.createReplacement(node.getOffset(), node.getLength(), replacement);
    TextSegment segment =
        new TextSegment(
            doc.getFormatter().getTextRegionAccess(), node.getOffset(), node.getLength());
    ITextReplacer replacer = new RevaDslFormatter.RevaLSTextReplacer(segment, textReplacement);

    doc.addReplacer(replacer);
  }

  private List<IAstRegion> getAstRegions(IFormattableDocument document, XExpression expression) {
    return StreamSupport.stream(
            document
                .getFormatter()
                .getTextRegionAccess()
                .regionForEObject(expression)
                .getAstRegions()
                .spliterator(),
            false)
        .toList();
  }

  private ISemanticRegion getSemanticRegion(IAstRegion astRegion) {
    return astRegion.getPreviousSemanticRegion().getNextSemanticRegion();
  }

  public ISemanticRegion regionForKeyword(String keyword, XExpression expression) {
    return textRegionExtensions.regionFor(expression).keyword(keyword);
  }

  static class RevaLSTextReplacer implements ITextReplacer {
    private final ITextSegment region;
    private final ITextReplacement replacement;

    @Override
    public ITextReplacerContext createReplacements(ITextReplacerContext it) {
      it.addReplacement(replacement);
      return it;
    }

    @Override
    public ITextSegment getRegion() {
      return region;
    }

    public RevaLSTextReplacer(ITextSegment region, ITextReplacement replacement) {
      this.region = region;
      this.replacement = replacement;
    }
  }
}
